Adding release tag

diff --git a/ado-pipeline/build/helpers/app-version.yaml b/ado-pipeline/build/helpers/app-version.yaml
--- a/ado-pipeline/build/helpers/app-version.yaml
+++ b/ado-pipeline/build/helpers/app-version.yaml
@@ -4,6 +4,9 @@ parameters:
 
 steps:
   - bash: |
+      set -euo pipefail
+
+      source ./fcp-pipeline-common/common/shared_functions.sh
       echo "##[debug]Setting app version for framework: ${{ parameters.appFrameworkType }}"
 
       case "${{ parameters.appFrameworkType }}" in
@@ -11,6 +14,21 @@ steps:
           echo "##[debug]Setting version for Node.js..."
           npmVersionString=$(grep version $(appName)/package.json | awk -F \" '{print $4}')
           echo "##vso[task.setvariable variable=appVersion]$npmVersionString"
+          
+          if [[ "$(isPr)" == "true" ]]; then
+            cd $(appName)
+            echo "##[debug]Checking the app version increment if this is a PR build"
+            MAIN_BRANCH_VERSION=$(git show origin/main:package.json | jq -r '.version')
+
+            echo "##[debug]Main branch version: $MAIN_BRANCH_VERSION"
+
+            if version_gt "$npmVersionString" "$MAIN_BRANCH_VERSION"; then
+              echo "##[debug]$npmVersionString is a valid version"
+            else
+              echo "##[error]$npmVersionString is not a valid version. Please increase the version number in package.json!"
+              exit 1
+            fi
+          fi
           ;;
         dotnet)
           echo "##[debug]Setting version for .NET..."
